### ISSUE TITLE
Documentation disappeared from docs.racket-lang.org

### ISSUE THREAD

**Issue by winny-** [vicampo/riposte#9]
Searching for "riposte" on https://docs.racket-lang.org/ yields no results.

Local documentation (via `raco doc riposte`) is unaffected.

**Comment by jessealama** [comment]
I've pushed a commit that (I hope) will fix this. I won't close the ticket till I can confirm that the docs are back. Thanks for letting me know!

**Comment by jessealama** [comment]
By the way, the [docs](https://docs.racket-lang.org/riposte/index.html) seem to be just fine (HTTP 200, output is what I expect). But when I look at Riposte's [entry](https://pkgs.racket-lang.org/package/riposte) in the Racket package catalog, I see:

    Checksum error An error occurred while updating the package checksum.

and a bunch of junk output. 

In any case, the commit I just pushed should help with that issue. We need to wait till the package server re-builds Riposte.

**Comment by winny-** [comment]
According to greghendershott on IRC the `brag` dependency was in a weird state yesterday and suggested it might be related.

**Comment by jessealama** [comment]
Yeah, that seems to have been it. Docs are back.
